# Generated by Django 4.1.4 on 2022-12-27 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_student_managers_rename_age_student_grade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.CharField(default='female', max_length=10),
        ),
        migrations.AlterField(
            model_name='student',
            name='studentName',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
