# Generated by Django 4.1.4 on 2022-12-23 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='student',
            managers=[
            ],
        ),
        migrations.RenameField(
            model_name='student',
            old_name='age',
            new_name='grade',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='department',
            new_name='studentName',
        ),
        migrations.RemoveField(
            model_name='student',
            name='fName',
        ),
        migrations.RemoveField(
            model_name='student',
            name='lName',
        ),
    ]
